# Generated by Django 5.2.17 on 2026-09-29 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(max_length=20)),
                ('estimated_minutes', models.IntegerField(default=30)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=1)),
                ('status', models.CharField(default='not_started', max_length=20)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='planner.topic')),
            ],
        ),
    ]
