# Generated by Django 5.2.17 on 2026-09-29 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_minutes', models.IntegerField(default=0)),
                ('confidence_before', models.IntegerField(default=1)),
                ('confidence_after', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='planner.task')),
            ],
        ),
    ]
