# Generated by Django 5.2.17 on 2026-09-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('available_hours_per_day', models.FloatField()),
                ('status', models.CharField(default='active', max_length=20)),
            ],
        ),
    ]
