# Generated by Django 5.2.17 on 2026-09-29 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='planner.module'),
        ),
        migrations.AlterField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='planner.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='has_practical',
            field=models.BooleanField(default=False),
        ),
    ]
